trigger:
- main

pool:
  name: java-agent
  demands:
    - Agent.Name -equals e-agent
stages:
- stage: Build
  displayName: compile
  jobs:
    - job: compile
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'Ecommerce_Store/pom.xml'
          goals: 'clean package -DskipTests'
          publishJUnitResults: false
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
 
- stage: test
  displayName: test 

  jobs:
   - job: test
     steps:
       - task: Maven@4
         inputs:
           azureSubscription: 'Aks-ecommerce'
           mavenPomFile: 'Ecommerce_Store/pom.xml'
           goals: 'test'
           publishJUnitResults: false
           javaHomeOption: 'JDKVersion'
           mavenVersionOption: 'Default'
           mavenAuthenticateFeed: false
           effectivePomSkip: false
           sonarQubeRunAnalysis: false
       
       