trigger:
- main

pool:
  name: java-agent
  demands:
    - Agent.Name -equals e-agent
stages:
- stage: Build
  displayName: compile
  jobs:
    - job: compile
      steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'Ecommerce_Store/pom.xml'
          goals: 'clean package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
 
